### ISSUE TITLE
Add pkgconf to the list of apt dependencies.

### ISSUE THREAD

**Issue by stankovictab** [milaq/XMousePasteBlock#10]
After `make` I got the error :
`make: pkg-config: No such file or directory`
So I just needed to add `pkgconf` to the `apt install` command.
That's it, thanks for making this! 👍🏻

**Comment by milaq** [comment]
Thanks for the headsup and the kind words.

I think we should not list common build dependencies here, i.e. we would also have to list `make` and its friends (e.g. `build-essential`). The `Building` section is only cited in order to point the user in the right direction, not to be a make tutorial.
