### ISSUE TITLE
feature-request: Running XMousePasteBlock on Wayland start-up

### ISSUE THREAD

**Issue by kwvg** [milaq/XMousePasteBlock#11]
## Description

I have attempted to set XMousePasteBlock (Huge thanks for making it! Appreciate it! :partying_face:) as something to run on graphical login on my new Debian 11 (Bullseye) installation which [on GNOME uses Wayland by default](https://wiki.debian.org/Wayland#GNOME_.28supported_since_3.20.2B-.29) so that means [I can't just plop `/usr/bin/xmousepasteblock` into `/etc/X11/xinit/xinitrc`](https://wiki.gnome.org/Initiatives/Wayland/SessionStart).

Also, GNOME Tweaks doesn't affect certain applications when disabling "middle click paste", see `@trollkotze`'s comment on [this answer](https://askubuntu.com/a/872165).  From what I've observed, it seems to affect Electron-based apps... of which, there are many.

I've attempted to...

* Try to create a service that `systemd` can start (and there were [attempts to do it before](https://gist.github.com/LMJW/6180692207896244e330ab26e7404f54)) but it didn't pan out cause [`systemd` executes services outside the GUI context](https://unix.stackexchange.com/a/360685), even after trying to make it run as "local user" instead of as `root` like it normally does
* Add to my `~/.bash_profile` but that requires me to open up a Terminal and doesn't count as "run on graphical login"
* Then after re-reading the "Session start" page on the GNOME website, I tried `xdg-autostart`.

  A tool where to test if my thing works, I have to run 

  ```bash
   ln -s ~/.config/autostart/xmousepasteblock.desktop ~/.local/share/applications/xmousepasteblock.desktop
   gtk-launch xmousepasteblock.desktop
   ```
   because `gtk-launch` cannot fathom taking in a file path and [`xdg-open` is `xdg-open`](https://askubuntu.com/a/5176) 

Option three is the _viable_ option it seems so.. here's the `xmousepasteblock.desktop` that I run 
```ini
[Desktop Entry]
Name=XMousePasteBlock
Comment=Userspace tool to disable middle mouse button paste in Xorg
Exec=/usr/bin/bash -c '(exec /usr/bin/xmousepasteblock &> /dev/null &)'
Icon=utilities-terminal
Terminal=false
Type=Application
Categories=Application
AutostartCondition=GSettings org.gnome.desktop.background show-desktop-icons
```

## Feature Request

A solution that executes `XMousePasteBlock` after login on a Wayland system and installed automatically when running `make install`

**Comment by milaq** [comment]
I don't think that would be reasonable.
This is a "keep it simple" tool and integrating autostart logic would be way over the top and produce much overhead on the developing side.

Thanks for the idea though.

**Comment by kwvg** [comment]
Thanks for considering it, funnily enough I've switched to Xfce which still uses X11 (for altogether different reasons... one of which is Issue #461 on https://github.com/TheAssassin/AppImageLauncher) and just plopped `/usr/bin/xmousepasteblock` into `/etc/X11/xinit/xinitrc` and now I'm back in business.

Thanks for considering it, though!
