### ISSUE TITLE
Fedora 33 dependencies

### ISSUE THREAD

**Issue by bencardoen** [milaq/XMousePasteBlock#14]
For Fedora the dependencies are slightly different
`sudo dnf install libX11-devel libev-devel libXi-devel`

Appreciate this pacakge, the unwanted copy paste caused a lot of issues when coding

**Comment by milaq** [comment]
Thanks for the heads-up!
I added your input to the readme: https://github.com/milaq/XMousePasteBlock/commit/94044984e4b3bd4086f3d5636f53c3a3117051fd

Cheers
