### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by shootie22** [milaq/XMousePasteBlock#27]
middle-click pasting is single-handedly the MOST ANNOYING thing in Linux.
I can see the use case if you want to select text, have it automatically copied and paste it with middle click if you're working in a cli. but not if you are using your linux machine for web browsing, gaming etc.

so thank you so much for making this work. i've been trying to get it to work for weeks. thank you.
![image](https://github.com/milaq/XMousePasteBlock/assets/39218788/d7ebc2d9-ef85-4fc9-83d3-617a08abfb3b)

**Comment by milaq** [comment]
Thanks for the kind words :1st_place_medal:

**Comment by RedSnt** [comment]
Totally agree. It's a weird thing to steal a mouse button, something you can't even configure your way out of, just for one purpose.  
XMousePasteBlock saves the day. In lieu of starting another thread, is there a changelog anywhere by chance? I upgraded from 1.2 to 1.4 and can't see other releases' changelog anywhere @milaq ?
