### ISSUE TITLE
Can't find systemctl service

### ISSUE THREAD

**Issue by dollo** [milaq/XMousePasteBlock#30]
Hi. Thanks for your work! I can run xmousepasteblock from the terminal and avoid mispasting content all over the place.

However, I cannot find the service to start or enable it using systemctl:

`Failed to start xmousepasteblock.service: Unit xmousepasteblock.service not found.`

I am using ubuntu 22.04.4 LTS

**Comment by marie-bnl** [comment]
The service in this repository is just provided in case you want to install it manually, `make install` does not install the systemctl service. I think the service should be installed automatically too, but that would be an issue for users who don't use systemd. Does anyone know how most packages install their systemd service without installing unwanted files if the user doesn't use it?

**Comment by capsey** [comment]
If you still need help, or anyone who stumbled here trying to figure out how to enable the service, in the directory you cloned the repo into and after running `sudo make install` run the following:

    sudo cp ./xmousepasteblock.service /etc/systemd/user/

and then enable the service for the user:

    systemctl --user enable --now xmousepasteblock.service

finally, check if the service is running using following command:

    systemctl --user status xmousepasteblock.service
