### ISSUE TITLE
Scrolling no longer works

### ISSUE THREAD

**Issue by geopic** [milaq/XMousePasteBlock#4]
The selection clipboard has been disabled, fortunately, but now the middle mouse button doesn't scroll. Is there any way to re-enable scrolling? This program would be perfect if it didn't disable scrolling as well.

**Comment by milaq** [comment]
Does this happen with a mouse wheel or a trackpoint button?

This should not disable middle mouse scrolling at all.

**Comment by geopic** [comment]
> Does this happen with a mouse wheel or a trackpoint button?
> 
> This should not disable middle mouse scrolling at all.

It happens with the mouse wheel.

**Comment by geopic** [comment]
Have managed to fix it by placing `xmousepasteblock` above `exec startkde` in `~/.xinitrc`...

**Comment by milaq** [comment]
Alright, glad that fixed it for you.

I'll have a look whether I can reproduce the issue.
