### ISSUE TITLE
Maybe add note about Klipper

### ISSUE THREAD

**Issue by nullstalgia** [milaq/XMousePasteBlock#5]
This did work for me after I unchecked "Prevent empty clipboard" in KDE's Klipper

![image](https://user-images.githubusercontent.com/20761757/79956135-95866480-8434-11ea-91d4-3055713fca09.png)

**Comment by milaq** [comment]
Heyhi,
totally missed this issue, sorry for that.

Thanks for the disclaimer  :1st_place_medal:, I added a bit of general readme text for that matter in https://github.com/milaq/XMousePasteBlock/commit/ac8a28c5411ce23738cd479fab1b456841637f0f.

Cheers
